[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
source ~/.msys/plugins/morokai.rc.vim
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.msys/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
au BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'start Firefox'
let g:previm_disable_default_css = 1
let g:previm_custom_css_path = '~/.msys/plugins/previm_custom.css'
nnoremap <silent> <Space>p :<C-u>PrevimOpen<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
nnoremap <silent> <Space>f :<C-u>Defx -listed -resume -buffer-name=mydefx
\ -show-ignored-files -split=tab ~/<CR>
'''
[plugins.ftplugin]
defx = '''
source ~/.msys/plugins/defx.rc.vim
'''

# ==========================================================
# denite
# ==========================================================

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_source = '''
source ~/.msys/plugins/denite.rc.vim
'''
hook_add = '''
source ~/.msys/plugins/denite_keymap.rc.vim
'''

[[plugins]]
repo = 'neoclide/denite-git'

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python_host_prog = ''
let g:python3_host_prog = system('which python3 | tr -d "\n"')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
source ~/.msys/plugins/deoplete.rc.vim
'''

# ==========================================================
# deoplete on Vim8
# ==========================================================

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
