[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.msys/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
au BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'start Firefox'
let g:previm_disable_default_css = 1
let g:previm_custom_css_path = '~/.msys/plugins/previm_custom.css'
nnoremap <silent> <Space>p :<C-u>PrevimOpen<CR>
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.msys/plugins/vimfiler.rc.vim
'''


# ==========================================================
# denite
# ==========================================================

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_source = '''
source ~/.msys/plugins/denite.rc.vim
'''
hook_add = '''
    nnoremap <silent> <Space>u :<C-u>Denite file_rec buffer<CR>
    nnoremap <silent> <Space>g :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
    nnoremap <silent> <Space>r :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
    nnoremap <silent> <C-n> :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=+1 -immediately<CR>
    nnoremap <silent> <C-b> :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=-1 -immediately<CR>
    nnoremap <silent> <Space>v :<C-u>Denite file_rec:~/.msys<CR>
    nnoremap <silent> <Space>w :<C-u>Denite file_rec:~/work<CR>
    call denite#custom#map('insert', '<C-j>','<denite:move_to_next_line>', 'noremap')
    call denite#custom#map('insert', '<C-k>','<denite:move_to_previous_line>', 'noremap')
    call denite#custom#map('insert', '<C-t>','<denite:do_action:tabopen>')
'''

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python_host_prog = ''
let g:python3_host_prog = system('which python3')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
source ~/.msys/plugins/deoplete.rc.vim
'''

# ==========================================================
# deoplete on Vim8
# ==========================================================

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
