[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
source ~/.msys/plugins/molokai.rc.vim
let loaded_matchparen = 1
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.msys/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
au BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'start Firefox'
let g:previm_disable_default_css = 1
let g:previm_custom_css_path = '~/.msys/plugins/previm_custom.css'
nnoremap <silent> <Space>p :<C-u>PrevimOpen<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_patterns = ['.myroot', '.myroot/', '.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
let g:rooter_silent_chdir = 1
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.msys/plugins/defx.rc.vim
'''
[plugins.ftplugin]
defx = '''
source ~/.msys/plugins/defx_keymap.rc.vim
'''

# ==========================================================
# denite
# ==========================================================

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_source = '''
source ~/.msys/plugins/denite.rc.vim
'''
hook_add = '''
source ~/.msys/plugins/denite_keymap.rc.vim
'''

[[plugins]]
repo = 'neoclide/denite-git'

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
source ~/.msys/plugins/deoplete.rc.vim
'''

# ==========================================================
# deoplete on Vim8
# ==========================================================

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
